[workspace]

members = [
    "hello",
    "goodbye",
    "ffi_to_c",
    "inline",
    "number_of_cores",
]

[profile.dev]
# all the following options are to reduce binary sizes
# see https://www.youtube.com/watch?v=b2qe3L4BX-Y
strip=true
debug=false
opt-level="s"
lto=true
codegen-units=1
